### ISSUE TITLE
Compute the anisotropy

### ISSUE THREAD

**Issue by CGH20171006** [tianjuxue/jax-am#26]
Previously, I had been using an earlier version of the allen-cahn file for programming computations. Initially, I was solely using the CPU for calculations, and there were no issues. However, after switching to a GPU, I found that it was taking a significant amount of time to compile when performing anisotropy calculations. As a result, I chose to upgrade the file to the latest version, and I no longer encountered the issue of long compilation times during calculations. However, during the calculation process, I encountered the following error (which did not occur in the original version). Could you please help me investigate the cause of this error? Or inform me of any other changes made when calling 'state_rhs' between the previous and current versions, aside from modifying the allen-cahn file.

Traceback (most recent call last):
  File "/home/cgh/projects/HTTD-PF/application/SingleCrystal_2/NotContainBase.py", line 333, in <module>
    output_next.inspect_sol(eta, eta0_next, TEMP, ts, increment + step_inds + 1)
  File "/home/cgh/mambaforge3/lib/python3.10/site-packages/pf_am/post_process.py", line 35, in inspect_sol
    raise ValueError(f"Found np.inf or np.nan in pf_sol - stop the program")
ValueError: Found np.inf or np.nan in pf_sol - stop the program

**Comment by ijku** [comment]
Did you make modifications based on the program under `/application/phase_field/solidification`? This program runs fine in my environment. Could you please specify which parameters you changed?

**Comment by CGH20171006** [comment]
I have change a lots of thing in my work, so I try to rewrite it in the example file. Do you have any suggestion about this？



---Original---
From: ***@***.***&gt;
Date: Sun, Aug 20, 2023 09:31 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [tianjuxue/jax-am] Compute the anisotropy (Issue #26)




 
Did you make modifications based on the program under /application/phase_field/solidification? This program runs fine in my environment. Could you please specify which parameters you changed?

**Comment by ijku** [comment]
Consider making step-by-step alterations to the code as you execute it on a GPU to isolate the source of the NaN values.

**Comment by CGH20171006** [comment]
&nbsp; &nbsp;After thoroughly investigating the problem, it seems that the issue arises during the computation of anisotropy. To isolate any potential causes from other parts of the codebase, I have simplified the code and separated it into two versions, which I have labeled as "Old" and "New."


&nbsp; &nbsp;In the "Old" version of the code, during the JIT compilation process, there is a significant increase in compilation time, whereas this issue does not occur during CPU compilation. On the other hand, in the "New" version of the code, compilation proceeds without any errors, but the anisotropy calculation does not yield the expected results.


I kindly request your assistance in reviewing both versions of the code to determine whether they are capable of achieving the same functionality.&nbsp;



20171006
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tianjuxue/jax-am"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月20日(星期天) 上午10:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tianjuxue/jax-am] Compute the anisotropy (Issue #26)





 
Consider making step-by-step alterations to the code as you execute it on a GPU to isolate the source of the NaN values.

**Comment by CGH20171006** [comment]
@ijku Specifically, I am puzzled by how the "New" version substitutes eta_pos_x - eta_neg_x for edge_x, and I am uncertain about why this replacement results in a significant reduction in compilation time. 
[Anisotropy.zip](https://github.com/tianjuxue/jax-am/files/12387430/Anisotropy.zip)
