### ISSUE TITLE
Memory leakage problem in \applications\fem\thermal

### ISSUE THREAD

**Issue by Jiangce2017** [tianjuxue/jax-am#4]
I found that when I run the thermal simulation the memory usage increase very fast. It might be caused by the lists that store inner_faces, external_faces, and all_faces. Python's List data structure is reported to consume larger memory than other data structure, like numpy.array. I am trying to replace the lists with numpy.array to see if the memory usage could be diminished.

**Comment by tianjuxue** [comment]
Closing this issue since no obvious bug of the library was found after testing.
