### ISSUE TITLE
Package Issues with jax-am

### ISSUE THREAD

**Issue by Vamsi717** [tianjuxue/jax-am#5]
When Trying to pip install the package getting an error sort of like this:
**ERROR: Cannot install jax-am==0.0.1 and jax-am==0.0.2 because these package versions have conflicting dependencies.**

Please Help me out with this on how to rectify this error.

![Package_error_Jax-am](https://user-images.githubusercontent.com/75405965/233996883-98d67d8c-0c99-4625-8fef-2457cb99824d.png)

**Comment by tianjuxue** [comment]
Thank you for your interest. At this stage, we recommend to try the library by "Install the most updated version from github", as described [Here](https://jax-am.readthedocs.io/en/latest/installation.html).

In your case, you only need one version of jax-am (you may uninstall the jax-am 0.0.1 version). Or you may create a new conda environment and try to install jax-am in the new environment.

**Comment by tianjuxue** [comment]
We have made [a video tutorial](https://jax-am.readthedocs.io/en/latest/tutorial.html) on the installation process of JAX-AM project. Closing the issue.
