### ISSUE TITLE
Issue with installation

### ISSUE THREAD

**Issue by SNMS95** [tianjuxue/jax-am#9]
I cloned the repo, created a bare (mini)conda environment.
The only packages I installed were jax and pip. 
When I tried to install using `pip install .`, the following error came up.

`Failed to build fenics-basix
**ERROR**: Could not build wheels for fenics-basix, which is required to install pyproject.toml-based projects`

**Comment by tianjuxue** [comment]
When creating the `conda` environment, please select a `Python` version. For example, python=3.8 usually works fine.
